### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by enyo** [gerichts-sv/questionnaire#51]
## Anonymisiertes Erhebungsblatt für Richtwerte bei Wohngebäuden:
 
Projektgröße
- [x] Wenn bei der Projektangabe im Feld „Sonstige Nutzungseinheiten“ eine Texteingabe mit einer Anzahl erfolgt ist, ist bei der Eingabe der Projektgröße in der Spalte WNF (m2) die Zahleneingabe „Erforderlich“ (anstatt derzeit: „Optional“).
 
Ausstattungsqualität
- [x] Folgende Info-Tooltips aus meinem E-Mail vom 22.03.2021 sind übersehen worden. Diese sollen auf dem Fragebogen bei der Auswahl „Detaillierte Angabe“ neben „normal“, „gehoben“ und „hochwertig“ sich jeweils hinter einem „?“ verbergen. Bitte die Texte „Normal:, Normal bis gehoben:, Gehoben:, Gehoben bis hochwertig:, Hochwertig:“ stets mit einem kleinen Anfangsbuchstaben beginnen.
 
- [x] normal: Info-Tooltip: Standard etwa nach Wohnbauförderungsrichtlinien (Mindestausstattung), keine Individual-Ausstattung, zeitgemäße Bauweise, bauphysikalische Mindestwerte nach jeweiliger Norm (Normalverbraucher)
 
- [x] gehoben: Info-Tooltip: Gediegene Ausführung, jedoch ohne wesentliche Luxuskomponenten und Designerelemente, sehr gute aktuelle bauphysikalische Eigenschaften und Installationsqualität, wirtschaftlicher Energiebedarf
 
- [x] hochwertig: Info-Tooltip: Architektendesign, energiesparende solide Bauweise, zusätzliche Energiequellen, Installationen solide und sehr umfangreich, beste Ausstattung, Luxuskomponenten
 
- [x] Diese Tooltips können auch als „?“ direkt neben der Überschrift „Ausstattungsqualität gesetzt werden (also analog wie bei den Bürogebäuden).
 
Kostenkennwerte
Info-Tooltip:
- [x] Die Überschrift „Kostenbereiche lt. ÖNORM B 1801-1“ löschen, diese haben Sie versehentlich aus Ihrem letzten Entwurf stehen gelassen.
- [x] Bitte die Tabelle genauso einfügen, wie sie grafisch im übermittelten Excel-File dargestellt ist. (also keine Gitternetzlinien im oberen Bereich, „Gesamt-kosten“ zweizeilig statt einzeilig; keine vertikale Linie zwischen „Grund“ und „GRD“; keine waagrechte Linie zwischen „Bauwerkskosten“ und „BWK“, Darstellung der waagrechten Linie zwischen „Baugliederung“ und „Grund“, Die Spalte „Herstellungskosten“ als Gesamtheit einrahmen).
 
- [x] Bauwerkskosten BWK: Falls hier optional eine Zahl eingegeben wird, so muss diese Eingabe kleiner sein als die Zahl der zuvor eingegebenen Herstellungskosten.
 
Darin enthaltene Erschwernisse / Besonderheiten:
- [x] Unter dem Wort „Betrag“ das Wort „Optional“ löschen. Falls jemand eine Besonderheit textlich eingibt, MUSS er in der Folge auch einen Betrag nennen, sodass in einem solchen Fall sich das Feld mit der Bezeichnung „Betrag“ öffnet und darunter stehen soll: „Eingabe erforderlich“.
Dieser Betrag MUSS durch eine Eingabeprüfung mathematisch kleiner sein als die Herstellungskosten. Dieser Betrag MUSS weiters auch durch eine Eingabeprüfung mathematisch kleiner sein als die Bauwerkskosten.
 
 
## Anonymisiertes Erhebungsblatt für Richtwerte bei Bürogebäuden
 
- [x] Als Tooltip steht noch „Wohngebäude“, da ist natürlich „Bürogebäude“ zu schreiben.
 
Geschoße oberirdisch:
- [x] Info-Tooltip: Geben Sie die Anzahl der oberirdischen Geschoße des Bürogebäudes ein.
 
Geschoße unterirdisch:
- [x] Info-Tooltip: Geben Sie die Anzahl der unterirdischen Geschoße des Bürogebäudes ein.
 
Gebäudeart zB.: Geschäftsgebäude, Industriegebäude, Industriegebäude,…
- [x] Diese Eingabe entfällt ersatzlos (Anmerkung: Da der Fragebogen nur Bürogebäude erfasst, ist die grundsätzliche Gebäudeart bereits definiert) Eine solche Eingabe war auch im Excel-Fragebogen für Bürogebäude nicht gegeben und dürfte es sich hier um einen Kopierfehler handeln.
 
- [x] „Aufgliederung in Nutzungsgruppen“ soll keine Überschrift in Fettbuchstaben sein und grafisch keine eigene Rubrik sein, sondern ein in Normalschrift gehaltener normaler Teil der Rubrik „Projektangaben“.
Aufgliederung in Nutzungsgruppen
der oberirdischen Geschoße in %
- [x] Info-Tooltip: Gliedern Sie die unterschiedlichen Nutzungsgruppen innerhalb der Gebäudeteile prozentuell nach Flächen auf.
Der eingegebene Prozentsatz für Büro soll größer gleich 50% sein.
 
Projektgröße
- [x] Erdgeschoß: den Info-Tooltip bitte ersatzlos löschen.
 
- [x] In der Spalte „BGF (m2)“ sollen alle Eingaben, also sowohl für das Erdgeschoß aber auch für die Obergeschoße bzw die Nebengeschoße und Untergeschoße verpflichtend sein, daher statt „Optional“ soll „Eingabe erforderlich“ stehen. Siehe hierzu auch die Ihnen vorliegende Excel-Tabelle, wo auch die Eingabe nach BGF erforderlich ist.
- [x] In der Spalte „NF (m²) sollen alle Eingaben (auch für das Erdgeschoß) „Optional sein“.
- [x] Die Spalte „BRI (m3)“ passt mit „Optional“.
 
Ausstattungsqualität
- [x] Info-Tooltip: Da stehen derzeit noch die Beschreibungen für die Einstufungen der gewerblich industriellen Gebäude. Bitte als Tooltip die Einstufungen von Bürogebäuden einfügen. Diese sind wie gehabt in der Ihnen vorliegenden Tabelle 2020_07_11_Fragebogen Herstellungskosten Bürogebäude unter dem Tabellenreiter „Ausstattungsstandard“ ersichtlich. Ich lege Ihnen diese sicherheitshalber nochmals bei.
 
- [x] Die Wörter einfach, mittel, hoch sollen sowohl im Fragebogen als auch im Info-Tooltip mit einem Kleinbuchstaben beginnen.
 
- [x] Im Eingabetool zur Ausstattungsqualität stehen noch die Beschreibungen und Aufgliederungen für Wohngebäude. Diese müssen natürlich abgeändert werden gemäß der Beschreibungen und Aufgliederungen für Bürogebäude. Siehe im File 2020_07_11_Fragebogen Herstellungskosten Bürogebäude unter dem Tabellenreiter „Ausst-Detail“. Die Prozentsätze zu den Bauteilen passen Sie zwischenzeitlich nach Ihrem eigenen Gefühl für den Entwurfsvorschlag um, da bekommen Sie noch eine genaue %-Vorgabe.
 
- [x] Die Überschrift lautet natürlich nicht: „Detaillierte Aufgliederung zur Einstufung von Wohngebäuden“, sondern „Detaillierte Aufgliederung zur Einstufung von Bürogebäuden“
 
Kostenkennwerte
Info-Tooltip:
- [x] Bitte den gleichen Fehler, wie oben bereits beschrieben, beheben.
 
- [x] Bauwerkskosten BWK: Falls hier optional eine Zahl eingegeben wird, so muss diese kleiner sein als die Zahl zu den zuvor eingegebenen Herstellungskosten.
 
Darin enthaltene Erschwernisse / Besonderheiten:
- [x] Unter dem Wort „Betrag“ das Wort „Optional“ löschen. Falls jemand eine Besonderheit textlich eingibt, MUSS er in der Folge auch einen Betrag nennen, sodass in einem solchen Fall sich das Feld mit der Bezeichnung „Betrag“ öffnet und darunter stehen soll: „Eingabe erforderlich“.
- [x] Dieser Betrag MUSS durch eine Eingabeprüfung mathematisch kleiner sein als die Herstellungskosten. Dieser Betrag MUSS weiters auch durch eine Eingabeprüfung mathematisch kleiner sein als die Bauwerkskosten.
 
 
## Anonymisiertes Erhebungsblatt für Richtwerte bei gewerblich industriellen Gebäuden
 
Meine Tooltips aus meinem E-Mail vom 22.03.2021 sind übersehen worden:
 
Geschoße oberirdisch
- [x] Info-Tooltip: Geben Sie die Anzahl der oberirdischen Geschoße des Gebäudes ein.
 
Geschoße unterirdisch
- [x] Info-Tooltip: Geben Sie die Anzahl der unterirdischen Geschoße des Gebäudes ein.
 
„Aufgliederung in Nutzungsgruppen“ soll keine Überschrift in Fettbuchstaben sein und grafisch keine eigene Rubrik sein, sondern ein in Normalschrift gehaltener normaler Teil der Rubrik „Projektangaben“.
Aufgliederung in Nutzungsgruppen
der oberirdischen Geschoße in %
- [x] Info-Tooltip: Gliedern Sie die unterschiedlichen Nutzungsgruppen innerhalb der Gebäudeteile prozentuell nach Flächen auf.
 
Projektgröße
- [x] Erdgeschoß: den Info-Tooltip bitte ersatzlos löschen.
 
- [x] In der Spalte „BGF (m2)“ sollen alle Eingaben, also sowohl für das Erdgeschoß aber auch für die Obergeschoße bzw die Nebengeschoße und Untergeschoße verpflichtend sein, daher statt „Optional“ soll „Eingabe erforderlich“ stehen. Siehe hierzu auch die Ihnen vorliegende Excel-Tabelle, wo auch die Eingabe nach BGF erforderlich ist.
In der Spalte „NF (m²) sollen alle Eingaben (auch für das Erdgeschoß) „Optional sein“.
Die Spalte „BRI (m3)“ passt mit „Optional“.
 
 
Ausstattungsqualität
- [x] Die Wörter einfach, mittel, hoch sollen sowohl im Fragebogen als auch im Info-Tooltip mit einem Kleinbuchstaben beginnen.
 
- [x] Im Eingabetool zur Ausstattungsqualität stehen noch die Beschreibungen und Aufgliederungen für Wohngebäude. Diese müssen natürlich gemäß meiner E-Mail vom 23.03.2021 abgeändert werden gemäß der Beschreibungen und Aufgliederungen für gewerblich industrielle Gebäude. Siehe im File 2020_12_13_Fragebogen Herstellungskosten gewerblich_industrielle_Gebäude_Entwurf Katzlinger unter dem Tabellenreiter „Ausst-Detail“. Die Prozentsätze zu den Bauteilen passen Sie zwischenzeitlich nach Ihrem eigenen Gefühl für den Entwurfsvorschlag um, da bekommen Sie noch eine genaue %-Vorgabe.
 
- [x] Die Überschrift lautet natürlich nicht: „Detaillierte Aufgliederung zur Einstufung von Wohngebäuden“, sondern „Detaillierte Aufgliederung zur Einstufung von gewerblich industriellen Gebäuden“
 
Kostenkennwerte
Info-Tooltip:
- [x] Bitte die Fehler wie oben bereits beschrieben beheben.
 
- [x] Bauwerkskosten BWK: Falls hier optional eine Zahl eingegeben wird, so muss diese kleiner sein als die Zahl zu den zuvor eingegebenen Herstellungskosten.
 
Darin enthaltene Erschwernisse / Besonderheiten:
- [x] Unter dem Wort „Betrag“ das Wort „Optional“ löschen. Falls jemand eine Besonderheit textlich eingibt, MUSS er in der Folge auch einen Betrag nennen, sodass in einem solchen Fall sich das Feld mit der Bezeichnung „Betrag“ öffnet und darunter stehen soll: „Eingabe erforderlich“.
- [x] Dieser Betrag MUSS durch eine Eingabeprüfung mathematisch kleiner sein als die Herstellungskosten. Dieser Betrag MUSS weiters auch durch eine Eingabeprüfung mathematisch kleiner sein als die Bauwerkskosten.
 
- [x] Anstatt: „Vielen Dank für Ihre Hilfe!“
Vielen Dank für Ihre Mitwirkung bei der Datenerhebung!

**Comment by close2** [comment]
Hauptgeschoße für Sonstige ist noch immer Optional

**Comment by close2** [comment]
Sorry verklickt...

**Comment by close2** [comment]
Auch gleich Beträge sind erlaubt.  Wahrscheinlich aber egal.


Bauwerkskosten BWK: Falls hier optional eine Zahl eingegeben wird, so muss diese Eingabe **kleiner** sein als die Zahl der zuvor eingegebenen Herstellungskosten.

 

Darin enthaltene Erschwernisse / Besonderheiten:

Unter dem Wort „Betrag“ das Wort „Optional“ löschen. Falls jemand eine Besonderheit textlich eingibt, MUSS er in der Folge auch einen Betrag nennen, sodass in einem solchen Fall sich das Feld mit der Bezeichnung „Betrag“ öffnet und darunter stehen soll: „Eingabe erforderlich“.

Dieser Betrag MUSS durch eine Eingabeprüfung mathematisch kleiner sein als die Herstellungskosten. Dieser Betrag MUSS weiters auch durch eine Eingabeprüfung mathematisch **kleiner** sein als die Bauwerkskosten.

**Comment by close2** [comment]
Vielen Dank für Ihre Mitwirkung bei der Datenerhebung!

kommt nicht:

![image](https://user-images.githubusercontent.com/364985/113767985-971d6b00-971f-11eb-90f8-5e6d2167b0f6.png)
